services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yogi15mintrack
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: super-secret-change-me
    ports:
      - "8080:8080"

volumes:
  db_data:
