version: "3.9"

services:
  test:
    image: maven:3.9.11-eclipse-temurin-21
    working_dir: /src
    volumes:
      - type: bind
        source: .
        target: /src
        read_only: true

      - type: bind
        source: ./test-reports
        target: /tmp/build/surefire-reports
        read_only: false

    env_file:
      - .env

    entrypoint: ["mvn", "-Ptest", "clean", "verify", "--no-transfer-progress"]
    container_name: yogi15mintrack-test

  depends_on:
    test-db:
      condition: service_healthy

    networks:
      - test-network

  test-db:
      image: mysql:8.0
      container_name: test-db
      environment:
        MYSQL_DATABASE: yogi15mintrack
        MYSQL_ROOT_PASSWORD: root
      restart: "no"
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s
      networks:
        - test-network
  networks:
    test-network:
      driver: bridge
