version: "3.9"

services:
  test:
    image: maven:3.9.11-eclipse-temurin-21
    working_dir: /src
    volumes:
      - type: bind
        source: .
        target: /src
        read_only: true

    env_file:
      - .env

    entrypoint: [ 
      "sh", 
      "-c", 
      "mvn -Ptest verify --no-transfer-progress \
        -Dproject.build.directory=/tmp/build \
        -Dsurefire.reportDirectory=/tmp/build/surefire-reports \
        -Dmaven.clean.skip=true \
        -DfailIfNoTests=false"
    ]

    container_name: yogi15mintrack-test
    depends_on:
      test-db:
        condition: service_healthy
    networks:
      - test-network

  test-db:
    image: mysql:8.0
    container_name: test-db
    environment:
      MYSQL_DATABASE: yogi15mintrack
      MYSQL_ROOT_PASSWORD: root
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
